# -*- coding: utf-8 -*-
"""API CEP-Gabarito.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lX_oPHM6Uo6mdiKiV_HWgDg3uo_1Y5dw

### Via CEP

https://viacep.com.br/

#### Consulta de informações de um CEP
"""

import pandas as pd
import requests

cep = "26.021-560"

cep = cep.replace("-", "").replace(".", "").replace(" ", "")

if len(cep) == 8:
    link = f'https://viacep.com.br/ws/{cep}/json/'

    requisicao = requests.get(link)

    print(requisicao)

    dic_requisicao = requisicao.json()

    uf = dic_requisicao['uf']
    cidade = dic_requisicao['localidade']
    bairro = dic_requisicao['bairro']
    print(cidade, bairro)
    
    
else:
    print("CEP Inválido")

"""#### Busca de CEP a partir de endereço"""

uf = "RJ"
cidade = "Rio de Janeiro"
endereco = "Rio Branco"

link = f'https://viacep.com.br/ws/{uf}/{cidade}/{endereco}/json/'

requisicao = requests.get(link)
print(requisicao)

dic_requisicao = requisicao.json()
print(dic_requisicao)

import pandas as pd

tabela = pd.DataFrame(dic_requisicao)
display(tabela)

